version: "3.1"
services:
    message_broker:
        image: eclipse-mosquitto
        network_mode: host
        ports:
            - 1883:1883
        volumes:
            - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
