version: "3.7"
services:
    client:
        image: nimashoghi/v2v-node:latest
        privileged: true
        stdin_open: true
        tty: true
        environment:
            MQTT_HOST: "mqtt://192.168.1.14"
            MY_TOPIC: "${CLIENT_ID}"
            ALL_TOPICS: "0,1,2,3,4"
            PRIVATE_KEY_LOCATION: "/app/keys/${CLIENT_ID}-private.bin"
            PUBLIC_KEY_LOCATION: "/app/keys/${CLIENT_ID}-public.bin"
            DEMO: "${DEMO}"
            SENSING_THRESHOLD: "5000"
        volumes:
            - "./keys/:/app/keys/"
            - socket:/v2v/
    reader:
        image: nimashoghi/v2v-cpp:latest
        privileged: true
        depends_on:
            - client
        volumes:
            - socket:/v2v/
volumes:
    socket:
